###
GET http://localhost:3000/

### get all users
GET http://localhost:3000/users/allUsers

### get user by username
GET http://localhost:3000/users/user/fede

### login / get token
POST http://localhost:3000/users/getToken
Content-Type: application/json

{
    "username": "george",
    "password": "santiagodecompostela"
}


### create user
POST http://localhost:3000/users/
Content-Type: application/json

{
    "username": "ferdin",
    "password": "ferdi",
    "confirmPassword": "ferdi"
}

### test authenticate
GET http://localhost:3000/users/authorization
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1MywiZXhwIjoxNzM4Njk0Nzg5LCJpYXQiOjE3Mzg2OTExODl9.T9JX5ZzvMOKrFp-gAJJkiwgAPzStSE0tPMR4GATrlI8


### create chat
POST http://localhost:3000/chat
Content-Type: application/json

{
    "name": "ultima prova chat di gruppo"
}

### get chats by user
GET http://localhost:3000/chat/365
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJleHAiOjE3MzkyOTAxNjMsImlhdCI6MTczOTI4OTg2M30.LATux23KNx79yPQE9Za4YNPNbx72ptHrp8XV1yj3DZE


### add user to chat
POST http://localhost:3000/chat/addUser
Content-Type: application/json

{
    "chatId": 9,
    "userId": 365
}

### create message
POST  http://localhost:3000/messages
Content-Type: application/json

{
    "chatId": 5,
    "userId": 12,
    "value": "hi"
}

### delete message
DELETE http://localhost:3000/messages
Content-Type: application/json

{
    "messageId": 6
}

### get message by chat id
GET http://localhost:3000/messages/5
